packages:
  - packages/**

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@iarna/toml': ^2.2.5
  '@ltd/j-toml': ^1.38.0
  '@monaco-editor/loader': ^1.4.0
  '@prettier/plugin-php': ^0.22.0
  '@readme/httpsnippet': ^7.1.2
  '@tauri-apps/api': ^2.0.0
  '@tauri-apps/cli': ^2.0.0
  '@tauri-apps/plugin-shell': ^2.0.0
  '@types/bcryptjs': ^2.4.2
  '@types/chrome': ^0.0.193
  '@types/crypto-js': 4.1.1
  '@types/csso': ^5.0.0
  '@types/firefox-webext-browser': ^94.0.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/http-proxy': ^1.17.10
  '@types/jmespath': ^0.15.0
  '@types/js-yaml': ^4.0.5
  '@types/jsrsasign': ^10.5.4
  '@types/jstoxml': ^2.0.2
  '@types/lodash': ^4.17.7
  '@types/netmask': ^2.0.5
  '@types/node': ^22.0.0
  '@types/pako': ^2.0.0
  '@types/punycode': ^2.1.4
  '@types/qs': ^6.9.7
  '@types/sm-crypto': ^0.3.0
  '@types/strict-uri-encode': ^2.0.0
  '@types/uuid': ^10.0.0
  '@types/valid-data-url': ^2.0.0
  '@types/ws': ^8.5.4
  '@types/yargs-parser': ^21.0.0
  '@vercel/node': ^2.9.12
  '@vitejs/plugin-vue': ^5.1.0
  '@vue-macros/reactivity-transform': ^1.0.0
  '@vue/runtime-core': ^3.5.0
  '@vueuse/core': ^11.0.0
  a-color-picker: ^1.2.1
  ajv: ^8.12.0
  ajv-i18n: ^4.2.0
  axios: ^1.7.0
  bcryptjs: ^2.4.3
  bignumber.js: ^9.1.1
  bs58: ^6.0.0
  chardet: ^2.0.0
  chinese-simple2traditional: ^2.2.0
  colord: ^2.9.3
  composerize-ts: ^0.6.2
  crc: ^4.2.0
  cron-parser: ^4.7.1
  cronstrue: ^2.21.0
  crypto-js: 4.1.1
  csso: ^5.0.5
  csv-parse: ^5.3.3
  csv-stringify: ^6.2.3
  dayjs: ^1.11.12
  decode-uri-component: ^0.4.0
  eslint: ^9.39.2
  ext-list: ^4.0.0
  hexy: ^0.3.4
  html-minifier-terser: ^7.2.0
  http-proxy: ^1.18.1
  ip6: ^0.2.10
  istextorbinary: ^9.5.0
  jmespath: ^0.16.0
  js-base64: ^3.7.4
  js-htmlencode: ^0.3.0
  js-yaml: ^4.1.0
  jsbarcode: ^3.11.5
  json-keys-sort: ^2.1.0
  json-to-properties: ^1.1.3
  json5: ^2.2.3
  jsonpath-plus: ^9.0.0
  jsonrepair: ^3.0.2
  jsrsasign: ^11.0.0
  jwt-decode: ^4.0.0
  lodash: ^4.17.21
  magic-bytes.js: ^1.0.13
  mathjs: ^13.0.0
  monaco-editor: ^0.51.0
  netmask: ^2.0.2
  normalize.css: ^8.0.1
  nzh: ^1.0.13
  pako: ^2.1.0
  php-array-reader: ^2.1.2
  pinia: ^2.0.29
  pinia-plugin-persistedstate: ^4.0.0
  pinyin-pro: ^3.13.0
  prettier: ^3.3.0
  prettier-plugin-java: 2.6.4
  punycode: ^2.3.1
  qr-code-styling: github:baiy/styled-qr-code
  qrcode-parser: ^2.0.4
  qs: ^6.11.0
  quicktype-core: ^23.0.0
  recursive-diff: ^1.0.8
  sm-crypto: ^0.3.11
  sortablejs: ^1.15.0
  sql-formatter: ^15.4.2
  store2: ^2.14.2
  strict-uri-encode: ^2.0.0
  svg-path-bounds: ^1.0.2
  text-decoding: ^1.0.0
  tippy.js: ^6.3.7
  tsup: ^8.2.4
  typescript: ^5.5.0
  ua-parser-js: ^2.0.9
  uglify-js-export: ^3.17.4
  ulid: ^2.3.0
  utools-api-types: ^3.0.0
  uuid: ^10.0.0
  valid-data-url: ^5.0.0
  vite: ^5.4.3
  vite-plugin-html-config: ^2.0.2
  vite-plugin-node-polyfills: ^0.22.0
  vite-plugin-pwa: ^0.20.5
  vite-svg-loader: ^4.0.0
  vue: ^3.5.0
  vue-draggable-next: ^2.1.1
  vue-router: ^4.4.0
  vue-tsc: ^2.1.0
  when-json-met-bigint: ^0.27.0
  workbox-build: ^7.1.1
  workbox-window: ^7.1.0
  ws: ^8.12.0
  x2js: github:abdolence/x2js
  xml-formatter: ^3.6.0
  yargs-parser: ^21.1.1
  zip-a-folder: ^1.1.5

catalogs:
  conflicts_axios_h1_5_0:
    axios: ^1.5.0

onlyBuiltDependencies:
  - esbuild
  - vue-demi
